server:
  port: 9001
eureka:
  instance:
    appName: PRODUCT-SERVICE
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
